
    create table app_user (
        is_enabled boolean,
        id bigint not null,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    create table assignment (
        driver_id bigint not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        route_id bigint not null unique,
        shipment_id bigint not null unique,
        start_time timestamp(6) not null,
        vehicle_id bigint not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table driver (
        license_expiration_date date,
        id bigint generated by default as identity,
        user_info_id bigint not null unique,
        license_number varchar(255) unique,
        phone_number varchar(255),
        primary key (id)
    );

    create table refresh_token (
        id integer generated by default as identity,
        expiry_date timestamp(6) with time zone,
        user_id bigint unique,
        token varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table routes (
        destination_latitude float(53),
        destination_longitude float(53),
        estimated_distance_km float(53) not null,
        origin_latitude float(53),
        origin_longitude float(53),
        estimated_duration_minutes bigint not null,
        id bigint generated by default as identity,
        destination_address varchar(255),
        origin_address varchar(255),
        status varchar(255) not null check (status in ('DRAFT','CALCULATED','ACTIVE','COMPLETED','CANCELED')),
        primary key (id)
    );

    create table shipment (
        shipment_value numeric(38,2),
        volume_m3 numeric(38,2),
        weight_kg numeric(38,2) not null,
        actual_delivery_date timestamp(6),
        expected_delivery_date timestamp(6),
        id bigint generated by default as identity,
        route_id bigint unique,
        description varchar(255),
        destination_address varchar(255) not null,
        origin_address varchar(255) not null,
        status varchar(255) not null check (status in ('PENDING','SCHEDULED','IN_TRANSIT','OVERDUE','DELIVERED','DELAYED','CANCELED')),
        tracking_number varchar(255) not null unique,
        primary key (id)
    );

    create table user_roles (
        application_user_id bigint not null,
        role_id bigint not null,
        user_id bigint not null
    );

    create table vehicle (
        fuel_consumption_liters_per_100km numeric(38,2),
        last_service_date date,
        load_capacity_kg numeric(38,2),
        model_year integer,
        current_driver_id bigint unique,
        current_mileage_km bigint,
        id bigint generated by default as identity,
        next_service_mileage_km bigint,
        fuel_type varchar(255),
        license_plate varchar(255) not null unique,
        make varchar(255) not null,
        model varchar(255) not null,
        primary key (id)
    );

    alter table if exists assignment 
       add constraint FKlxyhk53rm4gb54bfipxr2i8p8 
       foreign key (driver_id) 
       references driver;

    alter table if exists assignment 
       add constraint FK320nijic7fcow72xnld7schta 
       foreign key (route_id) 
       references routes;

    alter table if exists assignment 
       add constraint FK74jno1bew438olowitfrrkgow 
       foreign key (shipment_id) 
       references shipment;

    alter table if exists assignment 
       add constraint FK5s0h3p6bsdhaysqgk03dg10px 
       foreign key (vehicle_id) 
       references vehicle;

    alter table if exists driver 
       add constraint FKehly913071uevukgy4fx05c4s 
       foreign key (user_info_id) 
       references app_user;

    alter table if exists refresh_token 
       add constraint FK5wkt2p042y3lwltk29cvpxuh 
       foreign key (user_id) 
       references app_user;

    alter table if exists shipment 
       add constraint FKghw3j6lueyw6i2udq0973yg1j 
       foreign key (route_id) 
       references routes;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKj3mvebdkl4w67i9hn3t75fy1w 
       foreign key (application_user_id) 
       references app_user;

    alter table if exists user_roles 
       add constraint FK6fql8djp64yp4q9b3qeyhr82b 
       foreign key (user_id) 
       references app_user;

    alter table if exists vehicle 
       add constraint FKqal9l8b6utkrujkgidvju97ww 
       foreign key (current_driver_id) 
       references driver;

    create table app_user (
        is_enabled boolean,
        id bigint not null,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    create table assignment (
        driver_id bigint not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        route_id bigint not null unique,
        shipment_id bigint not null unique,
        start_time timestamp(6) not null,
        vehicle_id bigint not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table driver (
        license_expiration_date date,
        id bigint generated by default as identity,
        user_info_id bigint not null unique,
        license_number varchar(255) unique,
        phone_number varchar(255),
        primary key (id)
    );

    create table refresh_token (
        id integer generated by default as identity,
        expiry_date timestamp(6) with time zone,
        user_id bigint unique,
        token varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table routes (
        destination_latitude float(53),
        destination_longitude float(53),
        estimated_distance_km float(53) not null,
        origin_latitude float(53),
        origin_longitude float(53),
        estimated_duration_minutes bigint not null,
        id bigint generated by default as identity,
        destination_address varchar(255),
        origin_address varchar(255),
        status varchar(255) not null check (status in ('DRAFT','CALCULATED','ACTIVE','COMPLETED','CANCELED')),
        primary key (id)
    );

    create table shipment (
        shipment_value numeric(38,2),
        volume_m3 numeric(38,2),
        weight_kg numeric(38,2) not null,
        actual_delivery_date timestamp(6),
        expected_delivery_date timestamp(6),
        id bigint generated by default as identity,
        route_id bigint unique,
        description varchar(255),
        destination_address varchar(255) not null,
        origin_address varchar(255) not null,
        status varchar(255) not null check (status in ('PENDING','SCHEDULED','IN_TRANSIT','OVERDUE','DELIVERED','DELAYED','CANCELED')),
        tracking_number varchar(255) not null unique,
        primary key (id)
    );

    create table user_roles (
        application_user_id bigint not null,
        role_id bigint not null,
        user_id bigint not null
    );

    create table vehicle (
        fuel_consumption_liters_per_100km numeric(38,2),
        last_service_date date,
        load_capacity_kg numeric(38,2),
        model_year integer,
        current_driver_id bigint unique,
        current_mileage_km bigint,
        id bigint generated by default as identity,
        next_service_mileage_km bigint,
        fuel_type varchar(255),
        license_plate varchar(255) not null unique,
        make varchar(255) not null,
        model varchar(255) not null,
        primary key (id)
    );

    alter table if exists assignment 
       add constraint FKlxyhk53rm4gb54bfipxr2i8p8 
       foreign key (driver_id) 
       references driver;

    alter table if exists assignment 
       add constraint FK320nijic7fcow72xnld7schta 
       foreign key (route_id) 
       references routes;

    alter table if exists assignment 
       add constraint FK74jno1bew438olowitfrrkgow 
       foreign key (shipment_id) 
       references shipment;

    alter table if exists assignment 
       add constraint FK5s0h3p6bsdhaysqgk03dg10px 
       foreign key (vehicle_id) 
       references vehicle;

    alter table if exists driver 
       add constraint FKehly913071uevukgy4fx05c4s 
       foreign key (user_info_id) 
       references app_user;

    alter table if exists refresh_token 
       add constraint FK5wkt2p042y3lwltk29cvpxuh 
       foreign key (user_id) 
       references app_user;

    alter table if exists shipment 
       add constraint FKghw3j6lueyw6i2udq0973yg1j 
       foreign key (route_id) 
       references routes;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKj3mvebdkl4w67i9hn3t75fy1w 
       foreign key (application_user_id) 
       references app_user;

    alter table if exists user_roles 
       add constraint FK6fql8djp64yp4q9b3qeyhr82b 
       foreign key (user_id) 
       references app_user;

    alter table if exists vehicle 
       add constraint FKqal9l8b6utkrujkgidvju97ww 
       foreign key (current_driver_id) 
       references driver;

    create table app_user (
        is_enabled boolean,
        id bigint not null,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    create table assignment (
        driver_id bigint not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        route_id bigint not null unique,
        shipment_id bigint not null unique,
        start_time timestamp(6) not null,
        vehicle_id bigint not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table driver (
        license_expiration_date date,
        id bigint generated by default as identity,
        user_info_id bigint not null unique,
        license_number varchar(255) unique,
        phone_number varchar(255),
        primary key (id)
    );

    create table refresh_token (
        id integer generated by default as identity,
        expiry_date timestamp(6) with time zone,
        user_id bigint unique,
        token varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table routes (
        destination_latitude float(53),
        destination_longitude float(53),
        estimated_distance_km float(53) not null,
        origin_latitude float(53),
        origin_longitude float(53),
        estimated_duration_minutes bigint not null,
        id bigint generated by default as identity,
        destination_address varchar(255),
        origin_address varchar(255),
        status varchar(255) not null check (status in ('DRAFT','CALCULATED','ACTIVE','COMPLETED','CANCELED')),
        primary key (id)
    );

    create table shipment (
        shipment_value numeric(38,2),
        volume_m3 numeric(38,2),
        weight_kg numeric(38,2) not null,
        actual_delivery_date timestamp(6),
        expected_delivery_date timestamp(6),
        id bigint generated by default as identity,
        route_id bigint unique,
        description varchar(255),
        destination_address varchar(255) not null,
        origin_address varchar(255) not null,
        status varchar(255) not null check (status in ('PENDING','SCHEDULED','IN_TRANSIT','OVERDUE','DELIVERED','DELAYED','CANCELED')),
        tracking_number varchar(255) not null unique,
        primary key (id)
    );

    create table user_roles (
        application_user_id bigint not null,
        role_id bigint not null,
        user_id bigint not null
    );

    create table vehicle (
        fuel_consumption_liters_per_100km numeric(38,2),
        last_service_date date,
        load_capacity_kg numeric(38,2),
        model_year integer,
        current_driver_id bigint unique,
        current_mileage_km bigint,
        id bigint generated by default as identity,
        next_service_mileage_km bigint,
        fuel_type varchar(255),
        license_plate varchar(255) not null unique,
        make varchar(255) not null,
        model varchar(255) not null,
        primary key (id)
    );

    alter table if exists assignment 
       add constraint FKlxyhk53rm4gb54bfipxr2i8p8 
       foreign key (driver_id) 
       references driver;

    alter table if exists assignment 
       add constraint FK320nijic7fcow72xnld7schta 
       foreign key (route_id) 
       references routes;

    alter table if exists assignment 
       add constraint FK74jno1bew438olowitfrrkgow 
       foreign key (shipment_id) 
       references shipment;

    alter table if exists assignment 
       add constraint FK5s0h3p6bsdhaysqgk03dg10px 
       foreign key (vehicle_id) 
       references vehicle;

    alter table if exists driver 
       add constraint FKehly913071uevukgy4fx05c4s 
       foreign key (user_info_id) 
       references app_user;

    alter table if exists refresh_token 
       add constraint FK5wkt2p042y3lwltk29cvpxuh 
       foreign key (user_id) 
       references app_user;

    alter table if exists shipment 
       add constraint FKghw3j6lueyw6i2udq0973yg1j 
       foreign key (route_id) 
       references routes;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKj3mvebdkl4w67i9hn3t75fy1w 
       foreign key (application_user_id) 
       references app_user;

    alter table if exists user_roles 
       add constraint FK6fql8djp64yp4q9b3qeyhr82b 
       foreign key (user_id) 
       references app_user;

    alter table if exists vehicle 
       add constraint FKqal9l8b6utkrujkgidvju97ww 
       foreign key (current_driver_id) 
       references driver;

    create table app_user (
        is_enabled boolean,
        id bigint not null,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    create table assignment (
        driver_id bigint not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        route_id bigint not null unique,
        shipment_id bigint not null unique,
        start_time timestamp(6) not null,
        vehicle_id bigint not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table driver (
        license_expiration_date date,
        id bigint generated by default as identity,
        user_info_id bigint not null unique,
        license_number varchar(255) unique,
        phone_number varchar(255),
        primary key (id)
    );

    create table refresh_token (
        id integer generated by default as identity,
        expiry_date timestamp(6) with time zone,
        user_id bigint unique,
        token varchar(255),
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table routes (
        destination_latitude float(53),
        destination_longitude float(53),
        estimated_distance_km float(53) not null,
        origin_latitude float(53),
        origin_longitude float(53),
        estimated_duration_minutes bigint not null,
        id bigint generated by default as identity,
        destination_address varchar(255),
        origin_address varchar(255),
        status varchar(255) not null check (status in ('DRAFT','CALCULATED','ACTIVE','COMPLETED','CANCELED')),
        primary key (id)
    );

    create table shipment (
        shipment_value numeric(38,2),
        volume_m3 numeric(38,2),
        weight_kg numeric(38,2) not null,
        actual_delivery_date timestamp(6),
        expected_delivery_date timestamp(6),
        id bigint generated by default as identity,
        route_id bigint unique,
        description varchar(255),
        destination_address varchar(255) not null,
        origin_address varchar(255) not null,
        status varchar(255) not null check (status in ('PENDING','SCHEDULED','IN_TRANSIT','OVERDUE','DELIVERED','DELAYED','CANCELED')),
        tracking_number varchar(255) not null unique,
        primary key (id)
    );

    create table user_roles (
        application_user_id bigint not null,
        role_id bigint not null,
        user_id bigint not null
    );

    create table vehicle (
        fuel_consumption_liters_per_100km numeric(38,2),
        last_service_date date,
        load_capacity_kg numeric(38,2),
        model_year integer,
        current_driver_id bigint unique,
        current_mileage_km bigint,
        id bigint generated by default as identity,
        next_service_mileage_km bigint,
        fuel_type varchar(255),
        license_plate varchar(255) not null unique,
        make varchar(255) not null,
        model varchar(255) not null,
        primary key (id)
    );

    alter table if exists assignment 
       add constraint FKlxyhk53rm4gb54bfipxr2i8p8 
       foreign key (driver_id) 
       references driver;

    alter table if exists assignment 
       add constraint FK320nijic7fcow72xnld7schta 
       foreign key (route_id) 
       references routes;

    alter table if exists assignment 
       add constraint FK74jno1bew438olowitfrrkgow 
       foreign key (shipment_id) 
       references shipment;

    alter table if exists assignment 
       add constraint FK5s0h3p6bsdhaysqgk03dg10px 
       foreign key (vehicle_id) 
       references vehicle;

    alter table if exists driver 
       add constraint FKehly913071uevukgy4fx05c4s 
       foreign key (user_info_id) 
       references app_user;

    alter table if exists refresh_token 
       add constraint FK5wkt2p042y3lwltk29cvpxuh 
       foreign key (user_id) 
       references app_user;

    alter table if exists shipment 
       add constraint FKghw3j6lueyw6i2udq0973yg1j 
       foreign key (route_id) 
       references routes;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKj3mvebdkl4w67i9hn3t75fy1w 
       foreign key (application_user_id) 
       references app_user;

    alter table if exists user_roles 
       add constraint FK6fql8djp64yp4q9b3qeyhr82b 
       foreign key (user_id) 
       references app_user;

    alter table if exists vehicle 
       add constraint FKqal9l8b6utkrujkgidvju97ww 
       foreign key (current_driver_id) 
       references driver;
