-- DDL za bazu podataka (Definicija Sheme)

-- 1. Tablica za Korisnike (Users)
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          is_enabled BOOLEAN DEFAULT TRUE
);

-- 2. Tablica za Uloge (Roles)
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL UNIQUE
);

-- 3. Vezna tablica M:N za korisnike i uloge
CREATE TABLE user_roles (
                            application_user_id BIGINT NOT NULL, -- ISPRAVNO IME STUPCA
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (application_user_id, role_id),

    -- Vanjski ključevi
                            FOREIGN KEY (application_user_id) REFERENCES app_user(id) ON DELETE CASCADE,
                            FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- 4. Tablica za Osvježavanje Tokena (JWT)
CREATE TABLE refresh_token (
                               id BIGSERIAL PRIMARY KEY,
                               user_id BIGINT NOT NULL UNIQUE,
                               token VARCHAR(255) UNIQUE NOT NULL,
                               expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                               FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- 5. Tablica za Vozila (Vehicle)
CREATE TABLE vehicle (
                         id BIGSERIAL PRIMARY KEY,
                         license_plate VARCHAR(20) UNIQUE NOT NULL,
                         make VARCHAR(50) NOT NULL,
                         model VARCHAR(50) NOT NULL,
                         model_year INTEGER,
                         fuel_type VARCHAR(20),
                         load_capacity_kg DECIMAL(10, 2),

    -- Veza na vozača
                         current_driver_id BIGINT UNIQUE,
                         FOREIGN KEY (current_driver_id) REFERENCES app_user(id) ON DELETE SET NULL
);