DROP TABLE IF EXISTS shipment CASCADE;
DROP TABLE IF EXISTS routes CASCADE;  -- ← PROMJENA

CREATE TABLE IF NOT EXISTS routes (  -- ← PROMJENA
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      origin_address VARCHAR(255) NOT NULL,
    origin_latitude DECIMAL(10, 6) NOT NULL,
    origin_longitude DECIMAL(10, 6) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    destination_latitude DECIMAL(10, 6) NOT NULL,
    destination_longitude DECIMAL(10, 6) NOT NULL,
    estimated_distance_km DECIMAL(10, 2),
    estimated_duration_minutes BIGINT,
    status VARCHAR(50) NOT NULL
    );

-- ... ostale tablice ...

CREATE TABLE IF NOT EXISTS shipment(
                                       id BIGSERIAL PRIMARY KEY,
                                       tracking_number VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    weight_kg NUMERIC(10, 2),
    origin_address VARCHAR(255) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    expected_delivery_date TIMESTAMP WITH TIME ZONE,
                                         route_id BIGINT,
                                         CONSTRAINT fk_route FOREIGN KEY (route_id) REFERENCES routes (id)  -- ← PROMJENA
    );

CREATE TABLE IF NOT EXISTS assignment (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          driver_id BIGINT NOT NULL,
                                          vehicle_id BIGINT NOT NULL,
                                          shipment_id BIGINT NOT NULL UNIQUE,
                                          route_id BIGINT NOT NULL UNIQUE,
                                          start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                          end_time TIMESTAMP WITHOUT TIME ZONE,
                                          status VARCHAR(50) NOT NULL,

    FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE RESTRICT,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE RESTRICT,
    FOREIGN KEY (shipment_id) REFERENCES shipment(id) ON DELETE RESTRICT,
    FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE RESTRICT  -- ← PROMJENA
    );