-- DDL za kreiranje Sheme Baze Podataka (Schema.sql)
DROP TABLE IF EXISTS shipment CASCADE;
DROP TABLE IF EXISTS route CASCADE;
-- [1. DODATAK] Nova Tablica za Rute (Route)
CREATE TABLE IF NOT EXISTS route (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     origin_address VARCHAR(255) NOT NULL,
    origin_latitude DECIMAL(10, 6) NOT NULL,
    origin_longitude DECIMAL(10, 6) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    destination_latitude DECIMAL(10, 6) NOT NULL,
    destination_longitude DECIMAL(10, 6) NOT NULL,
    estimated_distance_km DECIMAL(10, 2),
    estimated_duration_minutes BIGINT,
    status VARCHAR(50) NOT NULL
    );

-- 1. Tablice za Autentifikaciju (Aplikacijski korisnik)
CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS app_user (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    is_enabled BOOLEAN DEFAULT TRUE
    );

CREATE TABLE IF NOT EXISTS user_roles (
                                          application_user_id BIGINT NOT NULL,
                                          role_id BIGINT NOT NULL,
                                          PRIMARY KEY (application_user_id, role_id),
    FOREIGN KEY (application_user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
    );

-- 2. Tablica za Osvježavanje Tokena (RefreshToken)
CREATE TABLE IF NOT EXISTS refresh_token (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id BIGINT NOT NULL UNIQUE,
                                             token VARCHAR(255) UNIQUE NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
    );

-- 3. Tablica za Vozački Profil (Driver)
CREATE TABLE IF NOT EXISTS driver (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_info_id BIGINT UNIQUE NOT NULL,
                                      license_number VARCHAR(255) UNIQUE,
    license_expiration_date DATE,
    phone_number VARCHAR(255),
    FOREIGN KEY (user_info_id) REFERENCES app_user(id) ON DELETE CASCADE
    );

-- 4. Tablica za Vozila (Vehicle)
CREATE TABLE IF NOT EXISTS vehicle (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       license_plate VARCHAR(255) UNIQUE NOT NULL,
    make VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    model_year INTEGER,
    fuel_type VARCHAR(50),
    load_capacity_kg DECIMAL(10, 2),
    current_driver_id BIGINT UNIQUE,
    FOREIGN KEY (current_driver_id) REFERENCES driver(id) ON DELETE SET NULL
    );

-- 5. Tablica za Pošiljke (Shipment) - KLJUČNA IZMJENA
CREATE TABLE IF NOT EXISTS shipment(
                          id BIGSERIAL PRIMARY KEY,
                          tracking_number VARCHAR(50) NOT NULL UNIQUE,
                          description TEXT,
                          weight_kg NUMERIC(10, 2),
                          origin_address VARCHAR(255) NOT NULL,
                          destination_address VARCHAR(255) NOT NULL,
                          status VARCHAR(50) NOT NULL,
                          expected_delivery_date TIMESTAMP WITH TIME ZONE,

                          route_id BIGINT,
                          CONSTRAINT fk_route FOREIGN KEY (route_id) REFERENCES route (id)
);

-- 6. Tablica za Dodjele (Assignment)
CREATE TABLE IF NOT EXISTS assignment (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          driver_id BIGINT NOT NULL,
                                          vehicle_id BIGINT NOT NULL,
                                          shipment_id BIGINT NOT NULL UNIQUE,
                                          route_id BIGINT NOT NULL UNIQUE,
                                          start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                          end_time TIMESTAMP WITHOUT TIME ZONE,
                                          status VARCHAR(50) NOT NULL,

    FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE RESTRICT,
    FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE RESTRICT,
    FOREIGN KEY (shipment_id) REFERENCES shipment(id) ON DELETE RESTRICT,
    FOREIGN KEY (route_id) REFERENCES route(id) ON DELETE RESTRICT
    );
-- /*ovdje mi je bez rute*/
-- -- -- DDL za kreiranje Sheme Baze Podataka (Schema.sql)
-- --
-- -- -- 1. Tablice za Autentifikaciju (Aplikacijski korisnik)
-- -- CREATE TABLE IF NOT EXISTS roles (
-- --                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                      name VARCHAR(255) NOT NULL UNIQUE
-- --     );
-- --
-- -- CREATE TABLE IF NOT EXISTS app_user (
-- --                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                         first_name VARCHAR(255) NOT NULL,
-- --     last_name VARCHAR(255) NOT NULL,
-- --     username VARCHAR(255) NOT NULL UNIQUE,
-- --     password VARCHAR(255) NOT NULL,
-- --     email VARCHAR(255) NOT NULL UNIQUE,
-- --     is_enabled BOOLEAN DEFAULT TRUE
-- --     );
-- --
-- -- CREATE TABLE IF NOT EXISTS user_roles (
-- --                                           application_user_id BIGINT NOT NULL,
-- --                                           role_id BIGINT NOT NULL,
-- --                                           PRIMARY KEY (application_user_id, role_id),
-- --     FOREIGN KEY (application_user_id) REFERENCES app_user(id) ON DELETE CASCADE,
-- --     FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
-- --     );
-- --
-- -- -- 2. Tablica za Osvježavanje Tokena (RefreshToken)
-- -- CREATE TABLE IF NOT EXISTS refresh_token (
-- --                                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                              user_id BIGINT NOT NULL UNIQUE,
-- --                                              token VARCHAR(255) UNIQUE NOT NULL,
-- --     expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
-- --     FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
-- --     );
-- --
-- -- -- 3. Tablica za Vozački Profil (Driver)
-- -- -- Driver se referencira na App_User (user_info_id)
-- -- CREATE TABLE IF NOT EXISTS driver (
-- --                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                       user_info_id BIGINT UNIQUE NOT NULL, -- Veza na app_user
-- --                                       license_number VARCHAR(255) UNIQUE,
-- --     license_expiration_date DATE,
-- --     phone_number VARCHAR(255),
-- --     FOREIGN KEY (user_info_id) REFERENCES app_user(id) ON DELETE CASCADE
-- --     );
-- --
-- -- -- 4. Tablica za Vozila (Vehicle)
-- -- -- Vehicle se referencira na Driver (current_driver_id)
-- -- CREATE TABLE IF NOT EXISTS vehicle (
-- --                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                        license_plate VARCHAR(255) UNIQUE NOT NULL,
-- --     make VARCHAR(255) NOT NULL,
-- --     model VARCHAR(255) NOT NULL,
-- --     model_year INTEGER,
-- --     fuel_type VARCHAR(50),
-- --     load_capacity_kg DECIMAL(10, 2),
-- --     current_driver_id BIGINT UNIQUE, -- Veza na DRIVER tablicu
-- --     FOREIGN KEY (current_driver_id) REFERENCES driver(id) ON DELETE SET NULL
-- --     );
-- --
-- -- -- 5. Tablica za Pošiljke (Shipment)
-- -- CREATE TABLE IF NOT EXISTS shipment (
-- --                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                         tracking_number VARCHAR(255) NOT NULL UNIQUE,
-- --     description VARCHAR(500),
-- --     weight_kg DECIMAL(10, 2) NOT NULL,
-- --     volume_m3 DECIMAL(10, 2),
-- --     origin_address VARCHAR(255) NOT NULL,
-- --     destination_address VARCHAR(255) NOT NULL,
-- --     status VARCHAR(50) NOT NULL,
-- --     expected_delivery_date TIMESTAMP WITHOUT TIME ZONE,
-- --     actual_delivery_date TIMESTAMP WITHOUT TIME ZONE
-- --     );
-- --
-- -- -- 6. Tablica za Dodjele (Assignment)
-- -- CREATE TABLE IF NOT EXISTS assignment (
-- --                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --                                           driver_id BIGINT NOT NULL,
-- --                                           vehicle_id BIGINT NOT NULL,
-- --                                           shipment_id BIGINT NOT NULL UNIQUE,
-- --                                           start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
-- --                                           end_time TIMESTAMP WITHOUT TIME ZONE,
-- --                                           status VARCHAR(50) NOT NULL,
-- --
-- --     FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE RESTRICT,
-- --     FOREIGN KEY (vehicle_id) REFERENCES vehicle(id) ON DELETE RESTRICT,
-- --     FOREIGN KEY (shipment_id) REFERENCES shipment(id) ON DELETE RESTRICT
-- --     );