-- 1. Obriši sve (REDOSLIJED JE BITAN!)
DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS refresh_token CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS driver CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS shipment CASCADE;
DROP TABLE IF EXISTS routes CASCADE;

-- 2. Osnovne tablice
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL
);

CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255),
                          first_name VARCHAR(255),
                          last_name VARCHAR(255),
                          username VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          is_enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE driver (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        is_available BOOLEAN DEFAULT TRUE
);

CREATE TABLE vehicle (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         make VARCHAR(255),
                         model VARCHAR(255),
                         license_plate VARCHAR(255)
);

CREATE TABLE shipment (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(255),
                          weight DOUBLE PRECISION
);

CREATE TABLE routes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        origin VARCHAR(255),
                        destination VARCHAR(255)
);

-- 3. Tablice s vezama (Foreign Keys)
CREATE TABLE refresh_token (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               token VARCHAR(255) NOT NULL,
                               expiry_date TIMESTAMP NOT NULL,
                               user_id BIGINT,
                               CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (user_id, role_id),
                            CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_user(id),
                            CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE assignment (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            driver_id BIGINT NOT NULL,
                            vehicle_id BIGINT NOT NULL,
                            shipment_id BIGINT NOT NULL UNIQUE,
                            route_id BIGINT NOT NULL UNIQUE,
                            start_time TIMESTAMP NOT NULL,
                            end_time TIMESTAMP,
                            status VARCHAR(50) NOT NULL,
                            CONSTRAINT fk_assign_driver FOREIGN KEY (driver_id) REFERENCES driver(id),
                            CONSTRAINT fk_assign_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle(id),
                            CONSTRAINT fk_assign_shipment FOREIGN KEY (shipment_id) REFERENCES shipment(id),
                            CONSTRAINT fk_assign_route FOREIGN KEY (route_id) REFERENCES routes(id)
);