-- TEST SCHEMA - Sve tablice

DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS shipment CASCADE;
DROP TABLE IF EXISTS routes CASCADE;
DROP TABLE IF EXISTS driver CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS refresh_token CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;

-- ✅ APP_USER sa IDENTITY
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255),
                          password VARCHAR(255),
                          first_name VARCHAR(255),
                          last_name VARCHAR(255),
                          email VARCHAR(255) NOT NULL UNIQUE,
                          is_enabled BOOLEAN
);

-- ✅ ROLES
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255)
);

-- ✅ USER_ROLES join table
CREATE TABLE user_roles (
                            application_user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            PRIMARY KEY (application_user_id, role_id),
                            FOREIGN KEY (application_user_id) REFERENCES app_user(id),
                            FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- ✅ DRIVER
CREATE TABLE driver (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_info_id BIGINT NOT NULL UNIQUE,
                        license_number VARCHAR(255) UNIQUE,
                        license_expiration_date DATE,
                        phone_number VARCHAR(255),
                        FOREIGN KEY (user_info_id) REFERENCES app_user(id)
);

-- ✅ VEHICLE
CREATE TABLE vehicle (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         license_plate VARCHAR(255) NOT NULL UNIQUE,
                         make VARCHAR(255) NOT NULL,
                         model VARCHAR(255) NOT NULL,
                         model_year INTEGER,
                         fuel_type VARCHAR(255),
                         load_capacity_kg DECIMAL(10, 2),
                         current_driver_id BIGINT UNIQUE,
                         current_mileage_km BIGINT,
                         last_service_date DATE,
                         next_service_mileage_km BIGINT,
                         fuel_consumption_liters_per_100km DECIMAL(5, 2),
                         FOREIGN KEY (current_driver_id) REFERENCES driver(id)
);

-- ✅ ROUTES
CREATE TABLE routes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        origin_address VARCHAR(255),
                        origin_latitude DOUBLE PRECISION,
                        origin_longitude DOUBLE PRECISION,
                        destination_address VARCHAR(255),
                        destination_latitude DOUBLE PRECISION,
                        destination_longitude DOUBLE PRECISION,
                        estimated_distance_km DOUBLE PRECISION NOT NULL,
                        estimated_duration_minutes BIGINT NOT NULL,
                        status VARCHAR(50) NOT NULL
);

-- ✅ SHIPMENT
CREATE TABLE shipment (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tracking_number VARCHAR(255) NOT NULL UNIQUE,
                          description VARCHAR(255),
                          weight_kg DECIMAL(10, 2) NOT NULL,
                          volume_m3 DECIMAL(10, 2),
                          shipment_value DECIMAL(10, 2),
                          origin_address VARCHAR(255) NOT NULL,
                          destination_address VARCHAR(255) NOT NULL,
                          status VARCHAR(50) NOT NULL,
                          expected_delivery_date TIMESTAMP,
                          actual_delivery_date TIMESTAMP,
                          route_id BIGINT UNIQUE,
                          FOREIGN KEY (route_id) REFERENCES routes(id)
);

-- ✅ ASSIGNMENT
CREATE TABLE assignment (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            driver_id BIGINT NOT NULL,
                            vehicle_id BIGINT NOT NULL,
                            shipment_id BIGINT NOT NULL UNIQUE,
                            route_id BIGINT NOT NULL UNIQUE,
                            start_time TIMESTAMP NOT NULL,
                            end_time TIMESTAMP,
                            status VARCHAR(50) NOT NULL,
                            FOREIGN KEY (driver_id) REFERENCES driver(id),
                            FOREIGN KEY (vehicle_id) REFERENCES vehicle(id),
                            FOREIGN KEY (shipment_id) REFERENCES shipment(id),
                            FOREIGN KEY (route_id) REFERENCES routes(id)
);

-- ✅ REFRESH_TOKEN
CREATE TABLE refresh_token (
                               id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               token VARCHAR(255),
                               expiry_date TIMESTAMP WITH TIME ZONE,
                               user_id BIGINT UNIQUE,
                               FOREIGN KEY (user_id) REFERENCES app_user(id)
);